### ISSUE TITLE
Possible bug when using variable products.

### ISSUE THREAD

**Issue by websitecareio** [alexmigf/stock-locations-for-woocommerce#10]
Hi. (Great plugin!)

When trying to get the plugin to show a message on a normal product, then it works fine. But when using variable products it doesn't work. 

How we use the plugin:
We update product stock using WP all import and settings the fields: _stock_at_XXXX (XXXX Being the ID of the TAX) to what ever level the stock is at in that location. THen currently manually setting the location afterwards on the product.

Note; we have tried to make a product without WP all import, to remove this as a possible issue.

Here is the location setting of a random product:
![location](https://user-images.githubusercontent.com/5160115/89808936-2fd0fc00-db3b-11ea-8791-63ad2e61aaff.PNG)

Product type:
![producttype](https://user-images.githubusercontent.com/5160115/89808933-2f386580-db3b-11ea-9c58-e5a3b01b14cc.PNG)

Stock settings: ![stocksettings](https://user-images.githubusercontent.com/5160115/89808942-31022900-db3b-11ea-8177-a0f6894a0739.PNG)

Variable stock: 
![stock](https://user-images.githubusercontent.com/5160115/89808940-30699280-db3b-11ea-8cf9-6ce4c4234ec7.PNG)

It should have 4 products in stock, but if we look at the product page:
![product page](https://user-images.githubusercontent.com/5160115/89808939-30699280-db3b-11ea-81b9-ee1530d0b0e3.PNG)

It say "på lager", but that is not the plugin that is saying that message. The message I wanted it to say is shown in this shortcode:
![shortcode](https://user-images.githubusercontent.com/5160115/89808937-2fd0fc00-db3b-11ea-9c34-818e2fa82b90.PNG)

But it does not come up at all. 

As I said we did try to make a product without wp all import, because I could have missed a field that was needed, but its the same for every variable product. The message is not shown and locationstock quantity is for some reason not above 0.

**Comment by websitecareio** [comment]
DId some more debugging and found out, that on the products where it does not work , it fails simply because is thinks its not a product. 

![NP](https://user-images.githubusercontent.com/5160115/89811261-af13ff00-db3e-11ea-82ce-91b379a7f026.PNG)

It does not get past the line that checks if its a product :/

**Comment by alexmigf** [comment]
Hi @websitecareio at this moment just works at a parent product level not with variations.

**Comment by websitecareio** [comment]
Hi. Thanks for replying. Sadly I did not notice this when reading about this great plugin. Is this a feature coming soon to this plugin or is it not planned?

**Comment by alexmigf** [comment]
Hi @websitecareio i will try to do it for a next release.

**Comment by websitecareio** [comment]
Good to hear. 

Another question: 
Is there any place where I can donate to you?

**Comment by alexmigf** [comment]
You're welcome :)

About the donation, one review would be fine and really appreciated: https://wordpress.org/support/plugin/stock-locations-for-woocommerce/reviews/#new-post

**Comment by alexmigf** [comment]
Already fixed in previous release.
