### ISSUE TITLE
Select warehouse for entire shop page

### ISSUE THREAD

**Issue by josuelony** [alexmigf/stock-locations-for-woocommerce#101]
Is it possible to select the location first and then only show products that are available into that specific location?

So for example I have product 
A [Spain, Germany, US]
B [Germany,US]

So I select my location to be "Spain", on the shop page only will show my product "A"

Is that possible with the plugin?

**Comment by alexmigf** [comment]
Not yet, you can follow this issue: https://github.com/alexmigf/stock-locations-for-woocommerce/issues/40
