### ISSUE TITLE
doubt about how to automate the stock

### ISSUE THREAD

**Issue by kevinBeltrame** [alexmigf/stock-locations-for-woocommerce#102]
Hello, how are you ? 
I wanted to know if the location of the product could be automatic where the user does not choose from where but is already automatically deducted from his country without any choice

**Comment by alexmigf** [comment]
Hi @kevinBeltrame, currently is not possible. Please follow this issue: https://github.com/alexmigf/stock-locations-for-woocommerce/issues/40
