### ISSUE TITLE
Products outofstock Taxonomy is not saved from product update woocommerce panel

### ISSUE THREAD

**Issue by jegschl** [alexmigf/stock-locations-for-woocommerce#15]
I had to add code for correctly save the product outofstock Taxonomy. Without this code the product stock status always is set to "outofstock".

In your file wp-content/plugins/stock-locations-for-woocommerce/src/classes/class-slw-stock-locations-tab.php:358 your code is this:

                 if( isset($_POST['_backorders']) && ( sanitize_text_field($_POST['_backorders']) === 'no' ) ) {
                    if( array_sum($input_amounts) > 0) {
                        update_post_meta($id, '_stock_status', 'instock');
                    } else {
                        update_post_meta($id, '_stock_status', 'outofstock');
                    }
                } else {
                    update_post_meta($id, '_stock_status', 'onbackorder');
                }

but  you have to update your code with this little code like this:

                if( isset($_POST['_backorders']) && ( sanitize_text_field($_POST['_backorders']) === 'no' ) ) {
                    if( array_sum($input_amounts) > 0) {
                        update_post_meta($id, '_stock_status', 'instock');

                       // Remove the link in outofstock taxonomy for the current product.
                        wp_remove_object_terms( $id, 'outofstock', 'product_visibility' ); 

                    } else {
                        update_post_meta($id, '_stock_status', 'outofstock');

                        // Add the link in outofstock taxonomy for the current product.
                        wp_set_post_terms( $id, 'outofstock', 'product_visibility', true ); 

                    }
                } else {
                    update_post_meta($id, '_stock_status', 'onbackorder');
                }

.....for your plugin update the "outofstock" taxonomy correctly

**Comment by alexmigf** [comment]
Hi @jegschl 

Thank you for your reporting, i will add those in the next release.

**Comment by jegschl** [comment]
> Hi @jegschl
> 
> Thank you for your reporting, i will add those in the next release.

Thanks to you for your god job on stock-locations-for-woocommerce wordpress plugin!
bye
