### ISSUE TITLE
Admin panel, WooCommerce Order page - "Invalid argument supplied for foreach()"

### ISSUE THREAD

**Issue by MarekBylica** [alexmigf/stock-locations-for-woocommerce#18]
Hi,

I just wanted to report that when we have no stock locations set for particular product there is a warning in admin panel -> WooCommerce orders -> Enter some order with missing stock location: "Invalid argument supplied for foreach()". Nothing scary but maybe worth mentioning. Great plugin tho :) 

![image](https://user-images.githubusercontent.com/22155560/91363601-45ae1480-e7fd-11ea-86b9-57df603dfcaa.png)

**Comment by alexmigf** [comment]
Hi @MarekBylica , thank you for the reporting, should be fixed on the next release.
