### ISSUE TITLE
Removing Item from Order Doesn't Return the Stock to The Location

### ISSUE THREAD

**Issue by clvnsm** [alexmigf/stock-locations-for-woocommerce#2]
Steps to reproduce:

1. Set stock for Product A in location A: 10
2. Add Order 1 pcs from Admin Panel, stock in location A: 9 
3. Edit Order from Admin Panel, remove Item from Order.
4. Total Woocommerce stock updated (back to 10) but stock in Location A not returning (still 9). 

Wordpress 5.4.1
Woocommerce 4.0.1

**Comment by alexmigf** [comment]
@clvnsm it's a known issue https://wordpress.org/support/topic/stock-management-has-bug/
