### ISSUE TITLE
Stock not being updated on variable product

### ISSUE THREAD

**Issue by MarekBylica** [alexmigf/stock-locations-for-woocommerce#20]
I think I found one more bug but this one seems to be quite important. When we have a variable product and we fill the order our stock should be automatically subtracted but it isn't. It works great in a simple product but in variable nothing changes, not the variation nor sum for the product. I can only change it's count manually.

![image](https://user-images.githubusercontent.com/22155560/91715843-c61e9d80-eb8e-11ea-9847-2444a2d931f8.png)

**Comment by alexmigf** [comment]
Hello @MarekBylica , do you have the auto order allocation enabled for that locations?

**Comment by MarekBylica** [comment]
Hi, @alexmigf.  In fact, after enabling this option, the stock for variable product started to change. However, I have two questions. 
1. Why in single product, when we don't have auto allocate enabled, the stock changes correctly when we manually assign a product?
2. Why in the variable product there is a "general" stock for all products (the one at the top), since we basically only use the sum of those specific for individual variations (the top stock does not change even with auto allocate).

Thanks for the response!

**Comment by alexmigf** [comment]
Hi, I'm on holidays right now, I will check that when I came back if you don't mind.

**Comment by alexmigf** [comment]
Hi @MarekBylica 

1) That's how it should work, if that doesn't happen with variations i have to investigate further.

2) The one in the top is the main product stock (like in the single product), not the overall stock of all the variations, that one is the WC default inside the inventory tab.
