### ISSUE TITLE
Stock does not synchronize when using the PolyLang and it's Woocommerce integration plugin

### ISSUE THREAD

**Issue by MarekBylica** [alexmigf/stock-locations-for-woocommerce#21]
Hey,

I have an issue using translations with Stock Locations. When I create a translation for some product it does not synchronize stock for different language versions of the product (even if in https://github.com/hyyan/woo-poly-integration plugin I have synchronization enabled). I'm not sure if it's a bug or it's an idea for some enchancement. I will be grateful for any answer.

**Comment by alexmigf** [comment]
Hi @MarekBylica 

The plugin doesn't support multilingual setups currently, i will need some time to do that.
