### ISSUE TITLE
Add support for multilangual setups

### ISSUE THREAD

**Issue by alexmigf** [alexmigf/stock-locations-for-woocommerce#22]
Currently the plugin doesn't support multilangual setups with WPML, Polylang or other, would be nice to have that in the future.

**Comment by MarekBylica** [comment]
Is there any workaround for this so I can sync my stock between translations of my products? 😢

**Comment by alexmigf** [comment]
Hello Marek,

What do you mean by translations? Multilingual?

Kind regards

MarekBylica <notifications@github.com> escreveu no dia quinta, 17/09/2020
à(s) 16:22:

**Comment by MarekBylica** [comment]
Yes, exacly. Using plugins like Polylang creates multiple product versions in different laguage and I want my stock to stay the same across every language. I know that Your plugin doesn't support this yet but I was wondering if there is some workaround?
Something to sync stock for all language versions of the product after I allocate some of them to an order.

**Comment by alexmigf** [comment]
Hi Marek,

To be honest I never tested with WPML or PLL, I can try to see that next
week but I don't promise a solution for that soon.

Kind regards

MarekBylica <notifications@github.com> escreveu no dia quinta, 17/09/2020
à(s) 20:14:

**Comment by MarekBylica** [comment]
Understand. Will check for update on this one 😄

**Comment by alexmigf** [comment]
Hi @MarekBylica are you able to test using WPML?
