### ISSUE TITLE
Add locations to REST API

### ISSUE THREAD

**Issue by alexmigf** [alexmigf/stock-locations-for-woocommerce#27]
https://wordpress.org/support/topic/warehouse-bin-locations/#post-13443121

**Comment by tmttechdept** [comment]
jdobbsy replied to that thread - https://wordpress.org/support/topic/warehouse-bin-locations/#post-13493922

If this can be possible will be really good.

**Comment by alexmigf** [comment]
I will try my best to include this on the next release.

**Comment by WarenGonzaga** [comment]
Agree! and as additional @alexmigf add button or switch to allow and disallow this feature.

**Comment by alexmigf** [comment]
https://github.com/alexmigf/stock-locations-for-woocommerce/pull/26
