### ISSUE TITLE
Stock Doesn't Reduce

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#28]
The only working part is when I set it up with auto order allocate. I have 3 locations and I want the admin to choose where to subtract the stock but it is not working on my end. Please help...

**Comment by alexmigf** [comment]
Hi @WarenGonzaga that's strange, can you show me a small screen recording of the issue?

**Comment by WarenGonzaga** [comment]
@alexmigf yes sure let me prepare it for you...

**Comment by WarenGonzaga** [comment]
@alexmigf how about a live copy of the site? I tried it to replicate it on WP Sandbox same behavior it works at first time then when you add another product it will not subtract again...

**Comment by alexmigf** [comment]
Sure @WarenGonzaga , please send me an [email](mailto:alexmigf@gmail.com) with the details.

**Comment by WarenGonzaga** [comment]
@alexmigf there's the initial clip for the issue... 

![Issue](https://i.imgur.com/ziH7INJ.gif)

The setup has woocommerce installed, and woocommerce pos

**Comment by WarenGonzaga** [comment]
@alexmigf expected behavior is that when you add stock number and hit enter it should record that value and subtract it to the stock location. But in my case when you hit enter nothing happens but ironically you will see a successful notice that the location stock has been updated.

**Comment by alexmigf** [comment]
@WarenGonzaga  that's unexpected for sure, a stage access will be most welcome to see what's going on.

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga that's unexpected for sure, a stage access will be most welcome to see what's going on.

I'm preparing a demo for you... I'll email it to you

**Comment by WarenGonzaga** [comment]
@alexmigf check your email for the credentials.

**Comment by WarenGonzaga** [comment]
@alexmigf it doesn't subtract but you will see this error...

![image](https://user-images.githubusercontent.com/15052701/94725677-bad9b000-038e-11eb-85f2-dd757ed33d6a.png)

**Comment by WarenGonzaga** [comment]
@alexmigf I found the issue... your plugin is not compatible with Woocommerce POS
