### ISSUE TITLE
Stock Locations App issues

### ISSUE THREAD

**Issue by simeonokwo** [alexmigf/stock-locations-for-woocommerce#31]
I was so glad when I saw this plugin and wouldn't mind going for its pro version if it exists. I however need some input. First is that it has been causing critical error on my site and I don't know how to resolve the error but I like to retain the plugin.

Secondly, how do I configure it to easily display the location of items on each product?

Thanks for your anticipated support

**Comment by alexmigf** [comment]
Hi @simeonokwo can you show me a screenshot of the error please?

**Comment by simeonokwo** [comment]
I have attached screenshots of before activating and after activating the
plugin

**Comment by alexmigf** [comment]
Hi @simeonokwo i believe you forgot to attach, i can't see them.

**Comment by simeonokwo** [comment]
I hope you're able to see the before and after activation here. I had to currently deactivate it because apart from the fatal error my end users complain a lot that certain registration portals weren't clicking through.
Majorly now I can identify that it affects the function of 
1. Woocommerce market place
2. Indeed affiliate pro
3. And the website as a whole.

I'll appreciate a quick attention because Stock Location is extremely useful to me too.

![Screenshot_20201012-205458](https://user-images.githubusercontent.com/69094857/95810355-aa1f2780-0d08-11eb-8ac7-d2882a96b05e.png)
![Screenshot_20201012-205415](https://user-images.githubusercontent.com/69094857/95810358-abe8eb00-0d08-11eb-948d-770eb5724a30.png)
![Screenshot_20201012-215537](https://user-images.githubusercontent.com/69094857/95810360-ac818180-0d08-11eb-9fac-11954ce5b659.png)

**Comment by alexmigf** [comment]
Hi @simeonokwo , can you look under **WooCommerce > Status > Logs** if you see any related error and paste here?

**Comment by simeonokwo** [comment]
Unfortunately, woocommerce does not seem to capture this error. I have however seen its effect before and after activation. 
Additionally I have captured and attached screens from my cpanel error log. I hope they are able to give insight. Due to the width the screenshots were captured in three and joined. Then the short video clip too. 

Thanks for the attention

![InShot_20201014_085951393](https://user-images.githubusercontent.com/69094857/95963149-36137b00-0dff-11eb-9dc9-b2ec6aeba101.jpg)

**Comment by simeonokwo** [comment]
https://youtu.be/mLeznE7UmjI. Here is the link to the screen record of the error log

**Comment by alexmigf** [comment]
Hi @simeonokwo can you copy and paste the error here please?

**Comment by simeonokwo** [comment]
[06-Oct-2020 01:56:14 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function SLW\SRC\Classes\woocommerce_wp_text_input() in /home/simeonokwo/public_html/wp-content/plugins/stock-locations-for-woocommerce/src/classes/class-slw-order-item.php:239
Stack trace:
#0 /home/simeonokwo/public_html/wp-content/plugins/stock-locations-for-woocommerce/src/classes/class-slw-order-item.php(138): SLW\SRC\Classes\SlwOrderItem->product_stock_location_inputs(3622, Array, Object(WC_Order_Item_Product), 77)
#1 /home/simeonokwo/public_html/wp-includes/class-wp-hook.php(287): SLW\SRC\Classes\SlwOrderItem->add_stock_location_inputs_wc_order(Object(WC_Product_Variation), Object(WC_Order_Item_Product), 77)
#2 /home/simeonokwo/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /home/simeonokwo/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/simeonokwo/public_html/wp-content/plugins/wc-frontend-manager/views/orders/wcfm-view-orders-details.php(538): do_action('woocommerce_adm...', Object(WC_Product_Variation) in /home/simeonokwo/public_html/wp-content/plugins/stock-locations-for-woocommerce/src/classes/class-slw-order-item.php on line 239

**Comment by alexmigf** [comment]
I don't see reason for that to happen since that function still exists in WooCommerce: https://github.com/woocommerce/woocommerce/blob/02cf0dfaed5923513de0c88add597d1560c2cfd2/includes/admin/wc-meta-box-functions.php#L19

**Comment by simeonokwo** [comment]
I do not doubt the existence as you have pointed out but I feel bad seeing
the negative effect upon activating the plugin on my website

**Comment by alexmigf** [comment]
@simeonokwo please [send me an email](mailto:alexmigf@gmail.com).

**Comment by alexmigf** [comment]
Due to inactivity I'm closing this.
