### ISSUE TITLE
Product page select box duplicates options - Product variations

### ISSUE THREAD

**Issue by javiercriado** [alexmigf/stock-locations-for-woocommerce#32]
Hello Alexandre,

great plugin!

I'm helping a friend of mine who has a small business in a jungle province from Perú with his website:
https://www.jsport.pro/producto/top-import-color/

1.- the problem is that each time you click on a product variation, in this case a product color, the stock locations select box keeps appending options.

I tried editing the plugin ajax function in script.js which executes when you click on a variation to delete all the options in the select first and then add the options available for that variation but I couldn't make it work.

![image](https://user-images.githubusercontent.com/11529913/95512925-291a0600-097f-11eb-9f69-cf70f5c18ed9.png)

2.- also the product locations select box doesn't show up in the cart page. maybe it's an error with my theme (XStore v. 6.3.5)

3.- suggestion: maybe there could be a select box in the header for the customer to select his location instead of selecting in each product page and the cart page a location for each item. an example of this is this website which asks you to select your location first with a popup before navigating the website: http://promart.pe/

![image](https://user-images.githubusercontent.com/11529913/95513054-51a20000-097f-11eb-8506-4ccd4dfacc71.png)

Thanks a lot!!

**Comment by alexmigf** [comment]
Hi @javiercriado , can you add it again so i can check?

**Comment by alexmigf** [comment]
Hi @javiercriado , can't reproduce, i believe because of the error below:

<img src="https://i.ibb.co/CWFsxbh/Captura-de-ecr-de-2020-10-13-21-18-45.png" alt="Captura-de-ecr-de-2020-10-13-21-18-45" border="0">

**Comment by javiercriado** [comment]
Hello @alexmigf, yes. they have

![image](https://user-images.githubusercontent.com/11529913/95995865-a28a7c00-0df7-11eb-8619-859c51dbec8c.png)
![image](https://user-images.githubusercontent.com/11529913/95995915-afa76b00-0df7-11eb-9994-aa8ecd90be77.png)
![image](https://user-images.githubusercontent.com/11529913/95996583-73c0d580-0df8-11eb-834a-7dadc59c65c5.png)
![image](https://user-images.githubusercontent.com/11529913/95996649-8a672c80-0df8-11eb-82a5-a4816bd7fe43.png)
![image](https://user-images.githubusercontent.com/11529913/95996926-d7e39980-0df8-11eb-8253-8dc5e124a6ca.png)
![image](https://user-images.githubusercontent.com/11529913/95997035-f6499500-0df8-11eb-93df-021137a2fd16.png)
![image](https://user-images.githubusercontent.com/11529913/95997089-05304780-0df9-11eb-8a08-2a942e82af19.png)

I couldn't reproduce the bad request error:
![image](https://user-images.githubusercontent.com/11529913/95996834-baaecb00-0df8-11eb-80fc-629397fc0294.png)

**Comment by alexmigf** [comment]
Hi @javiercriado can you show me your plugin settings?

**Comment by alexmigf** [comment]
@javiercriado can you send me your email to send you a new version of the plugin for testing?

**Comment by javiercriado** [comment]
yes!

![image](https://user-images.githubusercontent.com/11529913/96156919-4434ca80-0ed7-11eb-97fc-d9ec495118fb.png)

**Comment by javiercriado** [comment]
@alexmigf thank you!

the error is now fixed!!

![image](https://user-images.githubusercontent.com/11529913/96160152-3123f980-0edb-11eb-8ddc-7b28171880a7.png)
