### ISSUE TITLE
Stocks doesn't return on order cancel

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#35]
Hi there, it's me Waren again... there is a simple issue within the plugin... When an order has been allocated and when you cancel that order the stocks won't go back to the stocks data. Can you please take look into this issue?

**Comment by alexmigf** [comment]
Indeed, currently the plugin doesn't do anything on WC restore, i will need to add that in a future release.

**Comment by WarenGonzaga** [comment]
got it @alexmigf as additional can I help with the UI and UX of the plugin?

**Comment by mitzeitundohne** [comment]
yepp this is a showstopper bug :/ 
same happens during order too: see my bug report. the WC stock management is not controlled and finally lead to fully wrong stock amounts.

**Comment by alexmigf** [comment]
Hi @WarenGonzaga , send me an [email](mailto:alexmigf@gmail.com) if you would like to test the fix.

**Comment by WarenGonzaga** [comment]
Hi, @alexmigf I'm about to add automation to your build so everyone can test your builds easily without confusion. Yeah sure I will email you.

**Comment by mitzeitundohne** [comment]
email done. curious to test it :)

**Comment by despecial** [comment]
I would also appreciate to test this or get a release date 👍

**Comment by simsil64** [comment]
Hi Alex,

Was this fix released ?

**Comment by WarenGonzaga** [comment]
> Hi Alex,
> 
> Was this fix released ?

Yes already fixed it.

**Comment by simsil64** [comment]
Hi Alex,

I'm just looking at another related problem which is that stock is not put
back when an item is refunded. Can you please confirm whether that is part
of the functionality of this plugin currently. ?

Thanks for your help.

Regards
Simon

**Comment by alexmigf** [comment]
@simsil64 not yet implemented https://github.com/alexmigf/stock-locations-for-woocommerce/issues/63
