### ISSUE TITLE
Warning on specific location with insufficient stocks

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#41]
Example scenario:

When there is an order of 2 to a specific location with 1 stock it will still reduce on the stock resulting negative value.

Expected behavior it will not reduce on the location that insufficient on stock.

**Comment by WarenGonzaga** [comment]
This is the sample I'm talking about...

![test](https://user-images.githubusercontent.com/15052701/98763238-8ab51080-2414-11eb-9ce4-666606f58fd0.jpg)

**Comment by WarenGonzaga** [comment]
@alexmigf you might want to take a look into this?

**Comment by alexmigf** [comment]
@WarenGonzaga can you please update the plugin to the last version?

Could you please describe the steps to replicate the issue? This happens with auto allocation enabled or manual allocation?

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga can you please update the plugin to the last version?
> 
> Could you please describe the steps to replicate the issue? Does this happen with auto allocation enabled or manual allocation?

Hi @alexmigf, I'm using the latest plugin now. What I mean add a warning or error handling if the stock is insufficient in a stock location. This will prevent from having negative stock value.

**Comment by alexmigf** [comment]
I can't replicate that issue (negative stock values)

**Comment by WarenGonzaga** [comment]
Hi @alexmigf,

Basically, the point is add a warning if you are about to allocate the order in a less stock allocation.
In my case, the there is no Warning upon allocating the stocks to the less stock location based on order.

Got the idea or need example?

**Comment by alexmigf** [comment]
Hi @WarenGonzaga the plugin doesn't allow you to allocate more quantity then the available for the location, that's why I'm not understanding. Can you provide an example?

**Comment by WarenGonzaga** [comment]
> Hi @WarenGonzaga the plugin doesn't allow you to allocate more quantity then the available for the location, that's why I'm not understanding. Can you provide an example?

I'll send you an email for the sample installation with the same issue.

**Comment by alexmigf** [comment]
I didn't receive any email about this issue.

**Comment by WarenGonzaga** [comment]
@alexmigf I guess its all good for now...
