### ISSUE TITLE
Total amount on Product page

### ISSUE THREAD

**Issue by mitzeitundohne** [alexmigf/stock-locations-for-woocommerce#44]
Hi again ;)

Maybe a feature request: on product edit page after applying locations u show on top the Total amount of All locations. Why u not sum all amounts of each locations and display this? This could be Automated. 

And if for example the amount of any variable is 0 u could just not display the corresponding location for that variable on frontent instead of display "out of Stock "?

Rgds

**Comment by alexmigf** [comment]
Already available in the plugin settings, closing...
