### ISSUE TITLE
Change plugin settings location

### ISSUE THREAD

**Issue by mitzeitundohne** [alexmigf/stock-locations-for-woocommerce#49]
hi alex
another topic comes in my mind: why  you split the properties/seetings of you plugin to this different places? why you not just create an tab below "woocommerce" -> settings -> tab 

i saw this several times and other plugins using it. with that you can place everything on the same area and dont need to search it. dont understand why you placed it in general settings and products. because its very woocommerce related too.

rgds
sebastian

**Comment by alexmigf** [comment]
I agree that inside WooCommerce menu makes more sense.
