### ISSUE TITLE
stock locations not shown

### ISSUE THREAD

**Issue by tw1t611** [alexmigf/stock-locations-for-woocommerce#51]
I am using PHP 7.4. Just installed the plugin.
Woocommerce > Settings > Products > Inventory > Inventory Management is checked.
A location in Products > Stock locations was added.

Now I want to add the stock location to a product, but under Simple Product > Stock Locations the following warning shows up:
"You need to add a stock location to this product."

Am I doing something wrong? Please tell me, if you need something to reproduce.

**Comment by alexmigf** [comment]
Hi @tw1t611 did you added the location to the product in the sidebar (like categories)?

**Comment by tw1t611** [comment]
I did, furthermore there is an error message:
https://snipboard.io/fCaGov.jpg

**Comment by tw1t611** [comment]
After migration to an other hoster, the error war gone.
But I still can't add locations to the product.
Anything new from your site?

**Comment by jodzeee** [comment]
I found this confusing as well. Consider adding an arrow to the screenshot or a separate screenshot that makes it obvious where to add the locations. Or written instructions would help as well.

**Comment by alexmigf** [comment]
Hi @jodzeee sure, that's a great idea!

**Comment by alexmigf** [comment]
@jodzeee please contact me by [email](mailto:alexmigf@gmail.com), I will try to help you there.

**Comment by tw1t611** [comment]
@jodzeee wow, now I got it. Thank you very much.
@alexmigf sorry for the noise. Was just my fault.
