### ISSUE TITLE
Update stock in one location

### ISSUE THREAD

**Issue by Mikee93** [alexmigf/stock-locations-for-woocommerce#52]
Hey! im trying to update the stock from one location only, with the woocomerce API.

The problem is with i send the request to update the stock from "GDL" to 10, the stock from "GDL2" is deleted, i need to put the current stock in "GDL2" to work all together.

Any example to do this? thanks

**Comment by alexmigf** [comment]
Hi @Mikee93 I believe you need to keep the other locations with their values in the JSON even without updating them.
