### ISSUE TITLE
Inaccurate Stock Reporting

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#53]
For example... I know the logic. It shows the item with the stock location.

![image](https://user-images.githubusercontent.com/15052701/99889349-2ce3bc80-2c8f-11eb-9d1d-7ddb0924547c.png)

However, it will result in confusion. I would suggest adding reports for each stock location just like what you see on the product list.
So the shop manager knows exactly what to buy first or add stocks to the location.

**Comment by alexmigf** [comment]
Hi @WarenGonzaga from which plugin is that screen?

**Comment by WarenGonzaga** [comment]
> Hi @WarenGonzaga from which plugin is that screen?

I guess Woocommerce POS or is it from stock locations?

**Comment by alexmigf** [comment]
Not this plugin for sure. I have reports planned, but probably will have to wait a bit more.
