### ISSUE TITLE
Show stock value on Product location selection dropdown

### ISSUE THREAD

**Issue by alexmigf** [alexmigf/stock-locations-for-woocommerce#54]
https://wordpress.org/support/topic/show-stock-on-dropdown/#post-13710009

**Comment by marcelobaez** [comment]
Sorry if I'm being rude or not pollite, but whats the the point of having locations if the user select a quantity that exceeds the location stock?

**Comment by alexmigf** [comment]
Hi @marcelobaez the plugin will allow you to do that. In the cart will only show the locations that have stock available for the item quantity, in the product page it will auto select a location with stock available if the quantity is higher for the user selected location.
