### ISSUE TITLE
stock reduction -2

### ISSUE THREAD

**Issue by exscizo** [alexmigf/stock-locations-for-woocommerce#56]
hi, 
When i receive an order, i go to that order and do 1 on the article. what happens is, the location itself goes -1 but the normal stock goes -2.

**Comment by alexmigf** [comment]
Hi @exscizo which version of the plugin are you running?

**Comment by exscizo** [comment]
1.3.2

**Comment by WarenGonzaga** [comment]
This is the same issue with #41

**Comment by WarenGonzaga** [comment]
The stock allocation should warn the user if the stock allocation has no stock at all.
