### ISSUE TITLE
Import/Export csv

### ISSUE THREAD

**Issue by rickyruns** [alexmigf/stock-locations-for-woocommerce#57]
Hallo Alexandre,
your plugin is really good. I need to import & export products with location.
I use the standard function in woocommerce products, so i found necessary metas for stock, that works
Meta: _stock_at_1
Meta: _stock_at_2
Meta: _stock_at_3

I think, it is also important for visibility to write the location in csv.  i mean the field in the product-dropbox on the right side "location" in backend. There are too many products in the shop, doing all with click...

Is it possible in csv? Where? I searched in sql, but didn´t found something write.

I hope you can help me.

Thanks 
Ricky

**Comment by alexmigf** [comment]
Same as #48
