### ISSUE TITLE
Location pages not working

### ISSUE THREAD

**Issue by swagatac11** [alexmigf/stock-locations-for-woocommerce#58]
I am trying to view each location page but it is giving a 404 error.

http://massystores.wpengine.com/location/massy-stores-supercentre-warrens/

This is an example. Please help resolve hte problem.

**Comment by alexmigf** [comment]
@swagatac11 I believe you need to create a template, see docs: https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/

**Comment by swagatac11** [comment]
I need to create a custom template? Is there a shortcode to list the products per location?

**Comment by swagatac11** [comment]
Hi please help me out here. I want to list products in the frontend by location. How can I do that?

**Comment by alexmigf** [comment]
@swagatac11 contact me by [email](maulto:alexmigf@gmail.com) please.
