### ISSUE TITLE
Auto reduction on different Location

### ISSUE THREAD

**Issue by erwincaloing** [alexmigf/stock-locations-for-woocommerce#60]
I've set the 1 location per cart, then the customer choose only 1 location he wants.
But at the backend the order deduct on different location. Notes: I've set the required location

Please help.

**Comment by NariyalWala** [comment]
@erwincaloing I'm facing the same issue.

When you choose multiple products do all of them deducted from the same location or different? Can you confirm this? It will provide better clarity to @alexmigf

**Comment by erwincaloing** [comment]
Yes, correct.. How to required also the select location when the user wants
to direct check out without click View Cart

**Comment by erwincaloing** [comment]
Deducting from a different location when the user directed to check out.

**Comment by alexmigf** [comment]
@erwincaloing auto order allocation is enabled for the location choosed by the client and the other from the stock was deducted?

**Comment by erwincaloing** [comment]
> @erwincaloing I'm facing the same issue.
> 
> When you choose multiple products do all of them deducted from the same location or different? Can you confirm this? It will provide better clarity to @alexmigf

Nariyalwala, same location

**Comment by alexmigf** [comment]
@erwincaloing can you answer my previous question too?

**Comment by erwincaloing** [comment]
> @erwincaloing auto order allocation is enabled for the location choosed by the client and the other from the stock was deducted?

Yes @alexmigf , and Sometimes no green color label, like Client "Choosed location". then deducted from other location.

**Comment by alexmigf** [comment]
Hi @erwincaloing can you [email me](mailto:alexmigf@gmail.com)? Can't replicate this issue.

**Comment by erwincaloing** [comment]
Hi Sir.

I found the error,.

This is the scenario.

See my Settings on your Plugins

Show location selection in cart = YES

Make location selection in cart required. = Checked

Different location per cart item = NO

Show location selection in product page = NO

Show stock quantities in location selection in frontend = Checked

Auto delete unused product locations meta = none

Include location data in formatted item meta = YES

Enable location email notifications = UNCHECKED

Send copy of WC New Order email to location address = UNCHECKED




Problem 1:  Different location per cart item was set to *NO but still can
select different location*

Problem 2: Make location selection in cart required. = Checked , I've set
this as Checked to required the user to select the location to enable the
proceed button, but after clicking my drop down shipping option the
                proceed button was ENABLED.

Can you please required the location even if the shipping option was
selected first before the location.

**Comment by erwincaloing** [comment]
Hi Sir... deducted from different location.. but now

I found new error,.

This is the scenario.

See my Settings on your Plugins

Show location selection in cart = YES

Make location selection in cart required. = Checked

Different location per cart item = NO

Show location selection in product page = NO

Show stock quantities in location selection in frontend = Checked

Auto delete unused product locations meta = none

Include location data in formatted item meta = YES

Enable location email notifications = UNCHECKED

Send copy of WC New Order email to location address = UNCHECKED




Problem 1:  Different location per cart item was set to *NO but still can
select different location*

Problem 2: Make location selection in cart required. = Checked , I've set
this as Checked to required the user to select the location to enable the
proceed button, but after clicking my drop down shipping option the
                proceed button was ENABLED.

Can you please required the location even if the shipping option was
selected first before the location.

**Comment by erwincaloing** [comment]
[image: image.png]
The top image: After clicking the Shipping option the Proceed to Checkout
button was ENABLED even  the required location not selected Yet
[image: image.png]
I tried to create multiple order but 1 location only  for this cart. but
still i can select different location.

See my sample attached image

**Comment by alexmigf** [comment]
@erwincaloing is fixed, should be available in the next version, I will try to release as soon as possible.

**Comment by erwincaloing** [comment]
Hi any updates sir alexandre faustino

My second concern is, how to update the stocks on specific locations, using
php codes. may i know the database table stored the location name? so that
i can update it based on my php codes. Thanks
[image: image.png]

**Comment by alexmigf** [comment]
Hi @erwincaloing the locations stock is saved in the `postmeta` table with the key: `_stock_at_ID`
