### ISSUE TITLE
Stock item count positive but unable to add to cart

### ISSUE THREAD

**Issue by despecial** [alexmigf/stock-locations-for-woocommerce#61]
I am not sure if this has something to do with the WC stock meta but here are some screenshots attached.

In the backend the stock says 1 item left for size M or L
But when we try to add it to the cart none functions and on M our “out of stock” notifier shows up as if it only sees that for that size but not the others.

<img width="566" alt="Bildschirmfoto 2021-01-15 um 09 47 26" src="https://user-images.githubusercontent.com/4135109/104703422-988a5900-5717-11eb-84a9-559393c07f23.png">
<img width="343" alt="Bildschirmfoto 2021-01-15 um 09 47 41" src="https://user-images.githubusercontent.com/4135109/104703426-99bb8600-5717-11eb-9df9-09be1a94521f.png">
<img width="421" alt="Bildschirmfoto 2021-01-15 um 09 47 50" src="https://user-images.githubusercontent.com/4135109/104703430-9a541c80-5717-11eb-9084-290ad7a9595f.png">

**Comment by despecial** [comment]
Since it's a variable product I just checked the other tab and there we have different quantity settings, unable to change them. (disabled)

<img width="1167" alt="Bildschirmfoto 2021-01-15 um 10 02 20" src="https://user-images.githubusercontent.com/4135109/104704322-c91ec280-5718-11eb-9b8c-3e5c4269a930.png">

Any idea how to fix this and why it is happening?

**Comment by despecial** [comment]
More digging and searching other forums shows that one thing helps:
- disable inventory management on the product level

But there is still a problem: now the item is globally marked as out of stock even though 2 items are left

**Comment by alexmigf** [comment]
@despecial it seems that you have the variation global stock set as 0, please update the product post to update the levels.

**Comment by despecial** [comment]
@alexmigf so the correct setting is on the inventory tab to disable the inventory management and set the global stock for the location manually (I assumed your plugin calculates that and updates it)?

<img width="936" alt="Bildschirmfoto 2021-01-15 um 20 24 13" src="https://user-images.githubusercontent.com/4135109/104769587-d1561c80-576f-11eb-92eb-323e9c9c31c3.png">
<img width="710" alt="Bildschirmfoto 2021-01-15 um 20 24 22" src="https://user-images.githubusercontent.com/4135109/104769592-d31fe000-576f-11eb-8559-e10412a930f2.png">

**Comment by alexmigf** [comment]
@despecial product stock management must be enabled, and the plugin takes care of it.

**Comment by despecial** [comment]
As mentioned before: it doesnt. 
If we enable it, your plugin will reduce correctly from the single quantity count of the variable product but not update the WC stock count. its automatically "out of stock" even thought there are still items left.

**Comment by alexmigf** [comment]
@despecial that's not normal. Can you [send me an email](mailto:alexmigf@gmail.com)? I will need a temporary access to see that.

**Comment by despecial** [comment]
Got mail. Thanks for investigating...

**Comment by despecial** [comment]
Maybe you can use WooCommerce functions to update the main stock
https://github.com/woocommerce/woocommerce/blob/db3a78d7c70d4d9abcc313047bea260490a93a12/includes/wc-stock-functions.php#L152

`$new_stock = wc_update_product_stock( $product, $qty, 'decrease' );`
