### ISSUE TITLE
New stock update not able to add to default stock location

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#62]
Where to find or where to enable default stock location whenever a new update in stock level occur.

**Comment by alexmigf** [comment]
Hi @WarenGonzaga you have to set the priority under each location settings.

**Comment by WarenGonzaga** [comment]
> Hi @WarenGonzaga you have to set the priority under each location settings.

Where to edit the priority?

**Comment by alexmigf** [comment]
Should be at **Products > Stock Locations > Edit location > Location priority**

**Comment by WarenGonzaga** [comment]
> Should be at **Products > Stock Locations > Edit location > Location priority**

The issue is the only I can see is the slug option... no location priority.

**Comment by alexmigf** [comment]
Which version of the plugin are you running?
