### ISSUE TITLE
No notification emails are sent to the warehouse

### ISSUE THREAD

**Issue by brendangoosen** [alexmigf/stock-locations-for-woocommerce#65]
Hi There

Notification emails aren't being sent when auto order allocate is selected. I am not setting a priority. WooCommerce notification emails are working fine though.

**Comment by alexmigf** [comment]
@brendangoosen are you able to see the email log using a third party plugin like this one? https://wordpress.org/plugins/post-smtp/

**Comment by brendangoosen** [comment]
Thanks Alexandro, I will give that a try and get back to you.
