### ISSUE TITLE
Main stock not deducting 

### ISSUE THREAD

**Issue by ermosa** [alexmigf/stock-locations-for-woocommerce#66]
I´m having an issue that location stock can be deducted, but WC´s main stock remains the same.

Conditions/set up: 
The store is not multivendor,
all products are simple products,
location stock is deducted in the backend by the store manager who decides from where an order should be shipped,
running SLW latest version (1.4.3)
running WP 5.6.1

Example of successful scenario: 
the order comes in; the shop manager assigns a location from where to deduct the product in the backend, with that, the stock is deducted from that location and also from the main stock.
 
Problem: at the moment, it only deducts it from the location, but not from the main stock.

**Comment by alexmigf** [comment]
Hi @ermosa , thank you for reporting this!

I have found the culprit, just need some time to think the better way to address this fix. I will return back to you as soon as possible.

**Comment by alexmigf** [comment]
@ermosa [send me an email](mailto:alexmigf@gmail.com) so I can send you a copy for testing.
