### ISSUE TITLE
Stock Location Queries

### ISSUE THREAD

**Issue by robinv12010** [alexmigf/stock-locations-for-woocommerce#68]
Hi Alex,

Is there any way to allocate locations to a Zone in this plugin?
We can treat the state as one zone .All warehouse locations  under that state can be treated as a location and assign to that state(Zone).

How we can fulfil stock items from a particular warehouse location based  on Woocommerce checkout shipping address?
We need to find the warehouse locations  in that shipping state and fulfil the order from that particular warehouse location.

How we can sync stock inventory locations stock quantity using this plugin api?

Thank you
Robin

**Comment by alexmigf** [comment]
Hi @robinv12010 

Please use the [WP.org forums](https://wordpress.org/support/plugin/stock-locations-for-woocommerce/?view=all) for questions, Github is only for issues.

Thanks!
