### ISSUE TITLE
_stock_status goes always to onbackorder even when product is in stock

### ISSUE THREAD

**Issue by matthijs166** [alexmigf/stock-locations-for-woocommerce#71]
Hey there!

I love this plugin!

The problem I am having is that when a product is in stock and the backorder is allowed then de stock status is always going default to onbackorder. This needs to be instock if there is stock available. Only when there is no stock the status has to be onbackorder

This is also the default woocommerce behavior.

I have made a pull request to fix the issue. #72

**Comment by alexmigf** [comment]
Hi @matthijs166 thanks for your reporting! I didn't merge your code but I have fixed the issue based on it. It should be available in the next release.
