### ISSUE TITLE
pending order is not active, reduces stock

### ISSUE THREAD

**Issue by mtsport** [alexmigf/stock-locations-for-woocommerce#73]
Hi,

Problem with pending orders, product stock is discounted.

Thanks.

**Comment by alexmigf** [comment]
Hi @mtsport can you share a screenshot of the order details?

**Comment by mtsport** [comment]
Hi,

Hold stock disable:
![Hold stock](https://user-images.githubusercontent.com/575881/108029951-f8647000-6ff3-11eb-966a-8dacbe53e3e9.JPG)

I have the configuration to automatically assign the stock, it should not discount the stock since it is in pending payment status.
![Pending payment](https://user-images.githubusercontent.com/575881/108029776-b3d8d480-6ff3-11eb-868a-d994419bf0c0.JPG)

Regards

**Comment by alexmigf** [comment]
@mtsport can you send me an [email](mailto:alexmigf@gmail.com) so I can send you a new version for testing?
