### ISSUE TITLE
Not default location selected on simple products page only

### ISSUE THREAD

**Issue by dtejeda99** [alexmigf/stock-locations-for-woocommerce#74]
Hi,

Alex;

On simple products page, default location is not being selected by default.  Please see screenshots bellow:

Thanks,

Donny Tejeda

![Screenshot 2021-02-16 094315](https://user-images.githubusercontent.com/79149583/108070962-844dba80-703b-11eb-8279-7eed82c2a839.jpg)
![Screenshot 2021-02-16 094241](https://user-images.githubusercontent.com/79149583/108070964-857ee780-703b-11eb-9dc9-ecb5940674fb.jpg)
![Screenshot 2021-02-16 094140](https://user-images.githubusercontent.com/79149583/108070965-86177e00-703b-11eb-8dec-ddbb3068d520.jpg)

**Comment by alexmigf** [comment]
@dtejeda99 not supported yet, but I will add that as soon as possible.

**Comment by alexmigf** [comment]
Maybe the same as #67

**Comment by dtejeda99** [comment]
> @dtejeda99 not supported yet, but I will add that as soon as possible.

Thanks a lot.

**Comment by probaz** [comment]
hie @alexmigf how do i display products of a single location on a page?

**Comment by alexmigf** [comment]
Hi @probaz , can you please ask in the [forums](https://wordpress.org/support/plugin/stock-locations-for-woocommerce/?view=all)? Not much related with this issue.

**Comment by dtejeda99** [comment]
> @dtejeda99 not supported yet, but I will add that as soon as possible.

Hello, Alex.  Do you have an estimate of the time will take for this point to be supported?

**Comment by alexmigf** [comment]
Hi @dtejeda99 I will see if I can do that for the next release.

**Comment by alexmigf** [comment]
@dtejeda99 I believe that the default category is a feature from Yoast plugin and not properly from WordPress.

**Comment by dtejeda99** [comment]
Hi,

Alex;

This is the default location in the product page editor.  The location is added after installting stock for locations plugin.  Do you think this issue is related to YOAST SEO plugin?

Product page - backend

[cid:06acb42f-3164-48ad-94bb-2b05009d96ca]


Product page - Front end

[cid:d1b1dc13-e903-49c2-a1b8-00f5073bf6aa]

Regards,

Donny Tejeda

________________________________

De: Alexandre Faustino ***@***.***>
Enviado: martes, 16 de marzo de 2021 6:27 p. m.
Para: alexmigf/stock-locations-for-woocommerce ***@***.***>
Cc: dtejeda99 ***@***.***>; Mention ***@***.***>
Asunto: Re: [alexmigf/stock-locations-for-woocommerce] Not default location selected on simple products page only (#74)


@dtejeda99<https://github.com/dtejeda99> I believe that the default category is a feature from Yoast plugin and not properly from WordPress.

**Comment by alexmigf** [comment]
@dtejeda99 can't see the images.

What I see is, by default WordPress doesn't have the "Make default" setting for categories/locations, this just shows when you have Yoast installed.

**Comment by dtejeda99** [comment]
That't right.  I just disabled the Yoast SEO plugin and the make default category is not in product editor in backend anymore.  So that means that make default (from Yoast SEO) really doesn't make any change for locations selection in front end.  I see that the stock locations plug in selects by default a location with stock.



________________________________
De: Alexandre Faustino ***@***.***>
Enviado: miércoles, 17 de marzo de 2021 3:36 p. m.
Para: alexmigf/stock-locations-for-woocommerce ***@***.***>
Cc: dtejeda99 ***@***.***>; Mention ***@***.***>
Asunto: Re: [alexmigf/stock-locations-for-woocommerce] Not default location selected on simple products page only (#74)


@dtejeda99<https://github.com/dtejeda99> can't see the images.

What I see is, by default WordPress doesn't have the "Make default" setting for categories/locations, this just shows when you have Yoast installed.

**Comment by alexmigf** [comment]
@dtejeda99 I'm implementing a solution for that, will be available in the next release.

**Comment by alexmigf** [comment]
@dtejeda99 send me an [email](mailto:alexmigf@gmail.com) if you would like to test the new feature.
