### ISSUE TITLE
Out of stock status in front end even though there are stock available in warehouse location

### ISSUE THREAD

**Issue by dtejeda99** [alexmigf/stock-locations-for-woocommerce#77]
Hi,

Out of stock status in front end even though there are stock available in warehouse location. Is required to update twice in wordpress product backend for status to update correctly.

Please find screenshot attached with issue highlighted in red.

Thanks,

Donny Tejeda

![Out of stock status even though there area stock available in warehouse location](https://user-images.githubusercontent.com/79149583/111008618-e1e9d400-8367-11eb-86a8-6e9dcb507937.jpg)

**Comment by JUST1UNO** [comment]
I have the same problem, is there any quick fix for this? Not cool

**Comment by alexmigf** [comment]
@dtejeda99 or @JUST1UNO if you would like to test a fix please [email](mailto:alexmigf@gmail.com) me.
