### ISSUE TITLE
FontAwesome Issue

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#91]
Yes, I use it on my client and for some reason there is no icon showing on it. To resolve the issue I have to install this plugin from fontawesome. https://wordpress.org/plugins/font-awesome/ I guess you need to implement the same technique used in this plugin to the plugin.

**Comment by alexmigf** [comment]
Hi @WarenGonzaga which icon are you referring to?

**Comment by WarenGonzaga** [comment]
This one @alexmigf see pic below.

![image](https://user-images.githubusercontent.com/15052701/113604169-77326c80-9677-11eb-9939-9ed1e88771f5.png)

**Comment by alexmigf** [comment]
Again, I'm not having any issues locally with that, I assume you have some CSS conflicts there.

**Comment by WarenGonzaga** [comment]
> Again, I'm not having any issues locally with that, I assume you have some CSS conflicts there.

Yup, however I still report it so if anyone come across the same issue they can fix it immediately.

**Comment by Zodiac1978** [comment]
> Again, I'm not having any issues locally with that, I assume you have some CSS conflicts there.

Try a fresh installation without any other plugins/themes activated than default. Font Awesome is **not** loaded (even if the library is enabled in your settings). Additionally, the CSS should be optimized. 

If you validate this CSS (https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/css/admin-style.css) you get this warning:

> Family names containing whitespace should be quoted. If quoting is omitted, any whitespace characters before and after the name are ignored and any sequence of whitespace characters inside the name is converted to a single space. 

for line 2 and line 29.

The same problem is found here:
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/src/classes/class-slw-barcodes-tab.php#L70

The font is only loaded on the settings and the taxonomy page:
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/stock-locations-for-woocommerce.php#L264-L272

The other lines loading the Font Awesome font are only for the frontend:
https://github.com/fahadmahmood8/stock-locations-for-woocommerce/blob/4e451430f110e9f9cd2e4ec2c6234d1c581a67dc/src/stock-locations-for-woocommerce.php#L384-L387

So the font awesome files are not loaded on the edit product page.
