### ISSUE TITLE
Broken Settings Page

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#92]
![image](https://user-images.githubusercontent.com/15052701/113331303-5d7ce680-9352-11eb-971d-7d21da443742.png)

**Comment by alexmigf** [comment]
I don't have any issues there, probably some CSS conflict with other plugin. Please email me to see that.

**Comment by WarenGonzaga** [comment]
> I don't have any issues there, probably some CSS conflict with other plugin. Please email me to see that.

Might be, I would suggest use prefix on your CSS to prevent conflict with other CSS from other plugins.

**Comment by alexmigf** [comment]
It is using: https://github.com/alexmigf/stock-locations-for-woocommerce/blob/53642600be6533ba41696b550c98d24634f11e60/src/assets/css/admin/style.css#L37

**Comment by WarenGonzaga** [comment]
> It is using:
> 
> https://github.com/alexmigf/stock-locations-for-woocommerce/blob/53642600be6533ba41696b550c98d24634f11e60/src/assets/css/admin/style.css#L37

weird, I'll investigate it...

**Comment by WarenGonzaga** [comment]
@alexmigf for some reasons the stylesheet does not being loaded in admin area.

**Comment by WarenGonzaga** [comment]
@alexmigf closing this as it is already fixed.
