### ISSUE TITLE
Pick quantity from stock location after an order is placed

### ISSUE THREAD

**Issue by Salvo94** [alexmigf/stock-locations-for-woocommerce#93]
Hello, first this plugin is awesome for managing multi location stores!
But i have a little issue in a use case:
1) An user place an order and choice a location -> this is ok
2) The administrator check the order details and it appear the page for subtract quantities from a location. (check the attached image)
3) When the administrator type the quantity to subtract and update the order status, after the page refresh the quantity isn't subtracted.

I want to know is is my fault or how i can fix this.

Thanks in advance!

Best regards,
Salvatore Messina
[
![issue](https://user-images.githubusercontent.com/26455781/114745934-7b354d00-9d4f-11eb-894f-39fa5a1e1753.png)
](url)

**Comment by alexmigf** [comment]
@Salvo94 answered by email, closing this.

**Comment by joaoaviz** [comment]
Im having the same problem, may I know the fix ?

**Comment by fahadmahmood8** [comment]
Upcoming version will come with this issue fixed.
