### ISSUE TITLE
Unable to Allocate

### ISSUE THREAD

**Issue by WarenGonzaga** [alexmigf/stock-locations-for-woocommerce#96]
Hi @alexmigf for some reason after the update, I'm not able to allocate from the orders page.

**Comment by WarenGonzaga** [comment]
Here's the current error log I have...

```
PHP message: PHP Notice:  Constant WP_DEBUG_LOG already defined in /sites/client.com/files/wp-config.php on line 92" while reading response header from upstream, client: 00.00.00.00, server: client.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-client.sock:", host: "client.com", referrer: "https://client.com/wp-admin/edit.php?post_type=shop_order
```

What do you think @alexmigf?

**Comment by alexmigf** [comment]
@WarenGonzaga it's strange, but I don't see a correlation to this plugin. See here: https://serverpilot.io/docs/how-to-increase-max_input_vars/

**Comment by WarenGonzaga** [comment]
> @WarenGonzaga it's strange, but I don't see a correlation to this plugin. See here: https://serverpilot.io/docs/how-to-increase-max_input_vars/

Yeah already do that... I actually emailed you regarding the issue.

**Comment by alexmigf** [comment]
Ok, the other I can see, but it seems not related to me, but we continue in email.

**Comment by WarenGonzaga** [comment]
This is confirmed fixed! Thanks @alexmigf !
